### ISSUE TITLE
Create Sign Up/In/Out Routes for Users

### ISSUE THREAD

**Issue by chrisfandrade16** [atunney/pwa-capstone#10]
Create a route for users to sign up through our Python Django backend and chosen databasing tools. The input will be their role (can be represented though an enum of vehicle owner, shop owner, or shop employee), their unique email, their unique username, and their given password. The password will need to be encrypted. The output should result in a database account entry under the category of the role they selected, only if both the username and email are unique. If the database account entry is successfully created, an access token will be supplied back to the user, stored in their local storage for 14 days of automatic login.

For signing in, their email or username is required along with their password, or just an access token. For signing out, the access token will need to be supplied.

**Comment by Zhu-K** [comment]
Some rough ideas for the owner account system, applicable to frontend design and db schema

- owners should sign up their own account and shop profile
  - personal:
    - username
    - password
    - email
    - real name, phone, other contact info
    - mockup payment method
  - store profile:
    - name
    - address
    - description
    - services provided
    - contact
    - employees (this is where owners can create employee accounts with randomized passwords to hand to employees)

**Comment by harsh2204** [comment]
This is already done out of the box with Django. #18
