### ISSUE TITLE
Restructuring the code into src and split backend and frontend

### ISSUE THREAD

**Issue by harsh2204** [atunney/pwa-capstone#14]
The source code needs to live inside `src/`. Moreover, we need to split the FE And BE code into separate directories to keep them decoupled. We also need to setup docker and docker-compose files for the two services. There are projects already doing this by using a docker-compose file like [this](https://github.com/akshat2602/django-nextjs-boilerplate/blob/master/docker-compose.dev.yml), or [this one](https://github.com/yeganathan18/django-nextjs-boiler/blob/main/docker-compose.yml) with an nginx prox which will be required in our case.

**Comment by Zhu-K** [comment]
Will be closed once a README is provided for basic setup and usage instructions.
