### ISSUE TITLE
Setup Building and Deployment Webpage Process

### ISSUE THREAD

**Issue by chrisfandrade16** [atunney/pwa-capstone#3]
Vercel can be used to automatically build and deploy NextJS applications. Another option is to use Docker to create a build with a dockerized image which can be deployed to a web host that supports Docker, such as through AWS, Google Cloud Run, etc.

**Comment by Zhu-K** [comment]
Closed since this is currently handled with dockerized containers. For discussions regarding hosting see https://github.com/atunney/pwa-capstone/issues/5
